### ISSUE TITLE
Question: Is it possible to configure a different boilerplate for Typescript Lambda resources?

### ISSUE THREAD

**Issue by djheru** [stackery/typescript-sam#1]
Thanks for making such a great toolset. I've been using the graphical UI to create Lambda functions, and it looks like it's pulling this repo down as the code boilerplate. I'm sorry if this is off-topic, but is it possible to configure Stackery to pull down some configured repo as boilerplate when creating a new function resource? 

I've explored the blueprint concept, but that looks like it's more concerned with the stack structure overall. My goal is to have Stackery copy my own repo when I create a new `Function` so that I can use my preferred tooling, configuration and dependencies, instead of having to use a code generation tool like hygen or plop.

Thanks again! I just joined a team that's been using stackery in production for a while, and I'm looking forward to working with it.

**Comment by mbradburn** [comment]
When you drag a function onto the editor canvas, the source, pacakge.json, etc., are generated by the stackery application.  You're right that the blueprint isn't really oriented toward things that happen during the creation of a new single function, it's more of a starting point for the project that doesn't have any impact beyond the initial project creation.

Ryan Coleman is the person to talk to about this, he would be delighted to talk about your product feature ideas.  I'm reluctant to put his email address here, but you can contact him on slack or email support@stackery.io.
